# Sử dụng image node chính thức
FROM node:18

# Tạo và đặt làm thư mục làm việc
WORKDIR /appChat

# Copy package.json và package-lock.json vào thư mục làm việc
COPY package*.json ./

# Cài đặt dependencies
RUN npm install

# Copy toàn bộ mã nguồn
COPY . .

# Expose port (chỉnh sửa theo port mà ứng dụng của bạn sử dụng)
EXPOSE 3001

# Khởi động ứng dụng
CMD ["node", "./Server.js"]
