# Sử dụng image node chính thức có phiên bản bạn muốn sử dụng
FROM node:18-alpine

# Tạo thư mục làm việc trong container
WORKDIR /app

# Sao chép package.json và package-lock.json vào thư mục làm việc
COPY package*.json ./

# Cài đặt các dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn của ứng dụng vào thư mục làm việc
COPY . .

# Build ứng dụng
RUN npm run build

# Port mà ứng dụng sẽ chạy trên
EXPOSE 3000

# Lệnh để chạy ứng dụng khi container được khởi chạy
CMD ["npm", "start"]
