# Sử dụng image Node.js phiên bản 18.18.0 làm image cơ bản
FROM node:18.18.0

# Đặt thư mục làm việc trong container
WORKDIR /app



# Loại bỏ các file không cần thiết hoặc nhạy cảm
COPY . .

# Expose port mà ứng dụng sẽ chạy

EXPOSE 3003

# Khởi động ứng dụng
CMD ["node", "src/Server.js"]
